name: GitHub Action Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
    nroff-elves-scheduled:
        name: The Nroff Elves
        runs-on: ubuntu-latest
        steps:
          - name: Check out the git repo
            uses: actions/checkout@v2

          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJSON(github) }}
            run: |
              echo "============================="
              echo "$GITHUB_CONTEXT"
              echo "============================="
              git remote -v
              echo "============================="
              git status
              echo "============================="

          - name: Get the required packages
            run: sudo apt install -y pandoc perl hub

          - name: Build the nroff man pages
            run: .github/workflows/nroff-elves.sh
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
