name: GitHub Action Schedule

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
    nroff-elves-scheduled:
        name: The Nroff Elves
        runs-on: ubuntu-latest
        steps:
          - name: Debug
            env:
              output: ${{ toJSON(github.event) }}
            run: |
              echo JMS this is github.event
              echo "$output"

          - name: Check out the git repo
            uses: actions/checkout@v2

          - name: Get the required packages
            run: sudo apt install -y pandoc hub

          - name: Build the nroff man pages
            run: .github/workflows/nroff-elves.sh
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BASE_REF: ${{ github.event.repository.default_branch }}
